LISTEN_PORT: 3000
PROXY_CONFIG: 
  HOST: '127.0.0.1'
  PORT: 10809
MEDIA_LIST_PATH: './data/media_list.yaml'
ALIST_USE_PROXY: false
ALIST_API_TOKEN: alist-d5080314-138a-46ab-97ae-bd7c4fd14c239IHggfG7GgjKsN5HU7r3qpqmsOwXXucLSfI6lPxiP1PrAwsomPQU8sPtGLvxFOVr
ALIST_API_URL: http://192.168.1.76:9002
ALIST_MEDIA_PATH_LIST: 
  - /alidisk2/番剧
TMDB_USE_PROXY: true
TMDB_API_TOKEN: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiYTEwMzVkYWNjN2U2ZjlmZmZhMGEwNzU5ZjAzNDhkNyIsInN1YiI6IjY0NWI3YTJlZmUwNzdhNWNhYWUwOGY5ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.pxOXAzEC-Ib8p91K3oDn2SX3y7z1GI_afsVQdjItSwc'
DANDANPLAY_USE_PROXY: false
